baseURL: https://rd3ka.github.io/Portfolio/
languageCode: en-us
title: rvktiw
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: about-me
      name: About Me
      url: /about-me
      weight: 20
    - identifier: experience
      name: Experiences
      url: /experience
      weight: 30
    - identifier: projects
      name: Projects
      url: /projects
      weight: 40

params:
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  env: production

  profileMode:
    enabled: true
    title: "Raktim Deka"
    subtitle: "programmer üë®‚Äçüíª - tech enthusiast ‚å®Ô∏è  - linux evangelist üêß"
    imageUrl: "home/avataaars.svg"
    imageWidth: 200
    imageHeight: 200
    buttons:
      - name: Resume
        url: "https://drive.google.com/file/d/1icfDXNoltHr930BfRH90gjyArZbM8BiY/view?usp=share_link"

  hideDescriptionInList: false

  cover:
    hiddenInList: false
    hiddenInSingle: false

  socialIcons:
    - name: "email"
      url: "mailto:raktimdeka14@gmail.com"
    - name: "linkedin"
      url: "https://linkedin.com/in/rvktiw"
    - name: "github"
      url: "https://github.com/rd3ka"

markup:
  goldmark:
    renderer:
      unsafe: true
